# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - commit-msg
  - pre-commit
  - post-commit
  - post-rewrite
default_language_version:
    python: python3.11
default_stages:
  - commit
  - push
exclude: '.*migrations\/.*|.git'
minimum_pre_commit_version: 3.3.3

repos:
  # Automatically fix issues

  ## Poetry
  - repo: https://github.com/ScribeMD/pre-commit-hooks
    rev: 0.15.8
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install

  ## Markdown
  - repo: https://github.com/frnmst/md-toc
    rev: 8.2.0
    hooks:
      - id: md-toc
        args: [-p, 'cmark', '-l6']

  ## Python, TOML, Polyglot, Git
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      ### Automatically fix issues
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
        args:
        - --fix=crlf
      - id: trailing-whitespace
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"

      ### Check for issues
      - id: check-added-large-files
        args: [--enforce-all]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: forbid-submodules
      - id: no-commit-to-branch

      - id: check-yaml
        args: [--unsafe]
      - id: pretty-format-json
        args: [--autofix]
      - id: check-json
      - id: debug-statements
      - id: check-docstring-first

  # Check for issues

  ## Pre-commit
  - repo: meta
    hooks:
      - id: check-useless-excludes

  ## Git
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.7.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - post-commit
          - post-rewrite
          - push

  # - repo: https://github.com/jumanjihouse/pre-commit-hooks
  #   rev: 3.0.0
  #   hooks:
  #     - id: check-mailmap
  #     - id: forbid-binary
  #     - id: git-check
  #     - id: markdownlint

  ## CR
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.14.1
    hooks:
    -   id: django-upgrade
        args: [
          --target-version, "4.2"
        ]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 1.1.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.1.2
    hooks:
    - id: rstcheck
      additional_dependencies:
      - tomli==2.0.1

  # formatter and linter for HTML templates
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.32.1
    hooks:
      - id: djlint-django

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.4.18
    hooks:
      - id: checkov

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff
        args: [
          --config=pyproject.toml,
          --verbose
        ]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      args: [--config=pyproject.toml]

  - repo: https://github.com/adamchainz/blacken-docs
    rev: v1.12.1
    hooks:
    - id: blacken-docs
      additional_dependencies:
      - black==23.7.0

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      args: ["-c", "pyproject.toml", "-r", ".", ]
      additional_dependencies: ["bandit[toml]"]

  # Git commit message linter, checks your commit messages for style.
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    - id: gitlint

#   - repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.5.1
#     hooks:
#       - id: mypy
#         exclude: ^tests/
#         args: [
#           --strict,
#           --config-file=pyproject.toml
#         ]
#         additional_dependencies:
#           - pytest==7.1.2

ci:
  autoupdate_schedule: weekly
