fail_fast: true
exclude: '.*migrations\/.*|.git'
default_language_version:
    python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]
      - id: check-merge-conflict
      - id: detect-private-key
      # - id: fix-encoding-pragma
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=crlf']
        description: Forces to replace line ending by the UNIX 'lf' character
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-yaml
      - id: check-toml
      # - id: pretty-format-json
      #   args: [--autofix]
      # - id: check-json
      # - id: check-xml
      # - id: detect-aws-credentials

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.14.1
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.2"]

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.16
    hooks:
      - id: djlint-django

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff
        alias: autoformat
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      language_version: python3.11
      args: [--diff, --check]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      # additional_dependencies: [pep8-naming]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        require_serial: true
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--load-plugins=pylint_django",
            "--django-settings-module=bookstore.settings",
            "--ignore=manage.py",
          ]

#   - repo: https://github.com/pre-commit/mirrors-autopep8
#     rev: v2.0.4
#     hooks:
#     - id: autopep8

#   - repo: https://github.com/pre-commit/mirrors-prettier
#     rev: v3.0.2
#     hooks:
#     -   id: prettier

#   - repo: https://github.com/asottile/reorder_python_imports
#     rev: v3.10.0
#     hooks:
#       - id: reorder-python-imports

#   - repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.5.1
#     hooks:
#       - id: mypy
#         exclude: ^tests/
        # args: [--strict]
#         args: [--config-file=pyproject.toml]

#   - repo: https://github.com/hadialqattan/pycln
#     rev: v2.2.2
#     hooks:
#     -   id: pycln
#         args: [--config=pyproject.toml]

# Replaced by Ruff
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       #name: isort (python)

ci:
  autoupdate_schedule: monthly
