version: 2.1

workflows:
  build-deploy:
    jobs:
      - build
      - approval:
          type: approval
          requires:
            - build

jobs:
  build:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Ruff linting and Black formatting
          command: |
            poetry -V
