name: Auto Assign Issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ASSIGNEE: ${{ vars.DEFAULT_ISSUE_ASSIGNEE }}

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: pozil/auto-assign-issue@v1
      with:
        abortIfPreviousAssignees: true
        repo-token: GITHUB_TOKEN
        assignees: ASSIGNEE
