name: ci

on:
  pull_request:
  push:
    branches-ignore: main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: | 
          python -V
          python -m pipx install poetry
          poetry -V
      - name: Set up Python from Poetry config
        id: python_upgrade
        uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'
          cache: 'poetry'   # caching poetry dependencies
      - run: echo '${{ steps.python_upgrade.outputs.python-version }}'
      - name: Requirements check
        run: |
          python -V    
          poetry -V      
          poetry install
          poetry run pytest
          echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@v1

  lint:
    runs-on: ubuntu-latest
    needs: [requirements]
    steps:
      - uses: actions/checkout@v3
    #   - name: Set up Python 3.11
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: 3.11
      - name: Python & poetry version
        run: |
          python -V
          poetry -V
      - name: Ruff linting
        uses: chartboost/ruff-action@v1
        with:
          args: check --config=pyproject.toml --verbose
        # run: |
        #   python -m pip install --upgrade pip
        #   python -m pip install poetry
        #   poetry install 

  format:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Black style formatting
        uses: psf/black@stable
        with:
          options: --color --config=pyproject.toml --verbose
        # run: |
        #   python -m pip install --upgrade pip
        #   python -m pip install poetry
        #   poetry install --only dev 
        #   poetry run black .
        # env:
        #   CHANGED_FILES: ${{ steps.file_changes.outputs.added_modified }}

  test:
    runs-on: ubuntu-latest
    needs: [format]
    steps:
      - uses: actions/checkout@v3
      - name: Unit testing
        run: |
          python -V
          # poetry -V

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          python -V
          # poetry -V
