name: ci

on:
  pull_request:
  push:
    branches-ignore: main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    #   - name: Set up Python 3.11
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: 3.11
      - name: Ruff linting
        uses: chartboost/ruff-action@v1
        with:
          args: check --config=pyproject.toml --verbose
        # run: |
        #   python -m pip install --upgrade pip
        #   python -m pip install poetry
        #   poetry install 

  black:
    runs-on: ubuntu-latest
    needs: [ruff]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Black style formatting
        uses: psf/black@stable
        with:
          options: --color --config=pyproject.toml --verbose
        # run: |
        #   python -m pip install --upgrade pip
        #   python -m pip install poetry
        #   poetry install --only dev 
        #   poetry run black .
        # env:
        #   CHANGED_FILES: ${{ steps.file_changes.outputs.added_modified }}

  build:
    runs-on: ubuntu-latest
    needs: [black]
    steps:
      - uses: actions/checkout@v3
