name: Ruff linting and Black formatting
on:
  pull_request:
  push:
    branches-ignore: [main]
jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: chartboost/ruff-action@v1
        with:
          args: check --config=pyproject.toml --verbose

      - uses: psf/black@stable
        with:
          options: --diff --check --color --config=pyproject.toml --verbose
