name: Lint and format
on:
  pull_request:
  push:
    branches-ignore: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ruff linting
      uses: chartboost/ruff-action@v1
      with:
        args: check --config=pyproject.toml --verbose

    - name: Black formatting
      uses: psf/black@stable
      with:
        options: --check --verbose
