name: pull request on push

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ASSIGNEE: ${{ vars.DEFAULT_ISSUE_ASSIGNEE }}
  REVIEWER: ${{ vars.DEFAULT_PR_REVIEWER }}

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        id: open-pr
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: GITHUB_TOKEN
          target_branch: main
          title: "[#] <Feature>: PLACEHOLDER TITLE"
          template: ".github/PULL_REQUEST_TEMPLATE.md"
          reviewer: REVIEWER
          assignee: ASSIGNEE
          draft: true
          #label: "auto-pr"                               # Comma-separated list (no spaces)
          #milestone: "Milestone 1"                       # Milestone name
      # - name: pr-number
      #   run: echo ${{ steps.open-pr.outputs.pr_number }}
