name: Create or update a pull request on push
on: 
  push:
    branches-ignore:
      - main
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        id: open-pr
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          title: "[#] <Feature>: PLACEHOLDER TITLE"
          template: ".github/PULL_REQUEST_TEMPLATE.md"
          reviewer: ${{ vars.DEFAULT_PR_REVIEWER }}
          assignee: ${{ vars.DEFAULT_PR_ASSIGNEE }}
          draft: true
          #label: "auto-pr"                               # Comma-separated list (no spaces)
          #milestone: "Milestone 1"                       # Milestone name
      # - name: pr-number
      #   run: echo ${{ steps.open-pr.outputs.pr_number }}
